---

# This role deploys the mongod processes and sets up the replication set.

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the apt key for ubuntu
  apt_key: id=7F0CEB10 url="http://docs.mongodb.org/10gen-gpg-key.asc"
  when: ansible_os_family == "Debian"

- name: Install the python pycurl library
  apt: name=python-pycurl state=installed update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install the repository for Ubuntu mongodb
  apt_repository: repo="deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" state=present
  when: ansible_os_family == "Debian"
  
- name: Install the libselinux module
  yum: name=libselinux-python state=installed
  when: ansible_os_family == "RedHat"

- name: Create the repository for 10Gen
  copy: src=10gen.repo dest=/etc/yum.repos.d/10gen.repo
  when: ansible_os_family == "RedHat"

- name: Create the EPEL Repository.
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
  when: ansible_os_family == "RedHat"

- name: Create the mongod user
  user: name={{ mongo_user }} comment="MongoD"

- name: make sure the hostname is available in /etc/hosts
  lineinfile: dest=/etc/hosts regexp="{{ ansible_hostname }}" line="{{ hostvars[inventory_hostname].ansible_default_ipv4.address + " " + ansible_hostname }}" state=present

- name: Create the data directory for the mongod
  file: path={{ mongod_datadir_prefix }} owner={{ mongo_user }} group={{ mongo_group }} state=directory

- name: Install the mongodb package
  yum: name={{ item }} state=installed
  with_items: mongod_pkgs
  when: ansible_os_family == "RedHat"

- name: Install the mongodb package
  apt: name={{ item }} state=installed update_cache=yes
  with_items: mongod_pkgs
  when: ansible_os_family == "Debian"

- name: create data directory for mongodb
  file: path={{ mongod_datadir_prefix }}/mongo-{{ mongod_port }} state=directory owner={{ mongo_user }} group={{ mongo_group }}

- name: Create the mongodb startup file for Rhel
  template: src=mongod.j2 dest=/etc/init.d/mongod-{{ mongod_port }} mode=0655
  when: ansible_os_family == "RedHat"

- name: Create the mongodb startup file for Debian
  template: src=mongod_debian_init.j2 dest=/etc/init/mongodb-{{ mongod_port }}.conf mode=0655
  when: ansible_os_family == "Debian"

- name: Create the mongodb configuration file
  template: src=mongod.conf.j2 dest=/etc/mongod-{{ mongod_port }}.conf

- name: Copy the keyfile for authentication
  copy: src=secret dest={{ mongod_datadir_prefix }}/secret owner={{ mongo_user }} group={{ mongo_group }} mode=0400

- name: Start the mongodb service for redhat variants
  command: creates=/var/lock/subsys/mongod-{{ mongod_port }} /etc/init.d/mongod-{{ mongod_port }} start
  when: ansible_os_family == "RedHat"

- name: Start the mongodb service for Ubuntu variants
  service: name=mongodb-{{ mongod_port }} state=started
  when: ansible_os_family == "Debian"

- name: Create the file to initialize the mongod replica set
  template: src=repset_init.j2 dest=/tmp/repset_init.js
  when: mongod_replication and mongod_repl_master == ansible_hostname

- name: Pause for a while
  pause: seconds=40
  when: mongod_replication

- name: Initialize the replication set
  shell: /usr/bin/mongo --port "{{ mongod_port }}" /tmp/repset_init.js 
  when: mongod_replication and mongod_repl_master == ansible_hostname
